//Bamini (Tamil Bible) to Unicode Tamil Converter

function isTamilBibleFont(fontName)
{
  if (!fontName || typeof fontName !== "string") return false;
  return fontName.trim().toLowerCase() === "tamil bible";
}

// 309 Phonetic & Glyph replacement rules replicated from sskjames/tamilunicodeconverter
const baminiToUnicodeRules = 
[
  [/sp/g, "ளி"],
  [/hp/g, "ரி"],
  [/hP/g, "ரீ"],
  [/uP/g, "ரீ"],
  [/u;/g, "ர்"],
  [/h;/g, "ர்"],
  [/H/g, "ர்"],
  [/\+/g, "10"],
  [/nfs/g, "கௌ"],
  [/Nfh/g, "கோ"],
  [/nfh/g, "கொ"],
  [/fh/g, "கா"],
  [/fp/g, "கி"],
  [/fP/g, "கீ"],
  [/F/g, "கு"],
  [/\$/g, "கூ"],
  [/nf/g, "கெ"],
  [/Nf/g, "கே"],
  [/if/g, "கை"],
  [/f;/g, "க்"],
  [/f/g, "க"],
  [/nqs/g, "ஙௌ"],
  [/Nqh/g, "ஙோ"],
  [/nqh/g, "ஙொ"],
  [/qh/g, "ஙா"],
  [/qp/g, "ஙி"],
  [/qP/g, "ஙீ"],
  [/nq/g, "ஙெ"],
  [/Nq/g, "ஙே"],
  [/iq/g, "ஙை"],
  [/q;/g, "ங்"],
  [/q/g, "ங"],
  [/nrs/g, "சௌ"],
  [/Nrh/g, "சோ"],
  [/nrh/g, "சொ"],
  [/rh/g, "சா"],
  [/rp/g, "சி"],
  [/rP/g, "சீ"],
  [/R/g, "சு"],
  [/#/g, "சூ"],
  [/nr/g, "செ"],
  [/Nr/g, "சே"],
  [/ir/g, "சை"],
  [/r;/g, "ச்"],
  [/r/g, "ச"],
  [/n\[s/g, "ஜௌ"],
  [/N\[h/g, "ஜோ"],
  [/n\[h/g, "ஜொ"],
  [/\[h/g, "ஜா"],
  [/\[p/g, "ஜி"],
  [/\[P/g, "ஜீ"],
  [/\[\{/g, "ஜு"],
  [/\[_/g, "ஜூ"],
  [/n\[/g, "ஜெ"],
  [/N\[/g, "ஜே"],
  [/i\[/g, "ஜை"],
  [/\[\;/g, "ஜ்"],
  [/\[/g, "ஜ"],
  [/nQs/g, "ஞௌ"],
  [/NQh/g, "ஞோ"],
  [/nQh/g, "ஞொ"],
  [/Qh/g, "ஞா"],
  [/Qp/g, "ஞி"],
  [/QP/g, "ஞீ"],
  [/nQ/g, "ஞெ"],
  [/NQ/g, "ஞே"],
  [/iQ/g, "ஞை"],
  [/Q;/g, "ஞ்"],
  [/Q/g, "ஞ"],
  [/nls/g, "டௌ"],
  [/Nlh/g, "டோ"],
  [/nlh/g, "டொ"],
  [/lp/g, "டி"],
  [/lP/g, "டீ"],
  [/lh/g, "டா"],
  [/b/g, "டி"],
  [/B/g, "டீ"],
  [/L/g, "டு"],
  [/\^/g, "டூ"],
  [/nl/g, "டெ"],
  [/Nl/g, "டே"],
  [/il/g, "டை"],
  [/l;/g, "ட்"],
  [/l/g, "ட"],
  [/nzs/g, "ணௌ"],
  [/Nzh/g, "ணோ"],
  [/nzh/g, "ணொ"],
  [/zh/g, "ணா"],
  [/zp/g, "ணி"],
  [/zP/g, "ணீ"],
  [/Zh/g, "ணூ"],
  [/Z}/g, "ணூ"],
  [/nz/g, "ணெ"],
  [/Nz/g, "ணே"],
  [/iz/g, "ணை"],
  [/z;/g, "ண்"],
  [/Z/g, "ணு"],
  [/z/g, "ண"],
  [/njs/g, "தௌ"],
  [/Njh/g, "தோ"],
  [/njh/g, "தொ"],
  [/jh/g, "தா"],
  [/jp/g, "தி"],
  [/jP/g, "தீ"],
  [/Jh/g, "தூ"],
  [/Jh/g, "தூ"],
  [/J}/g, "தூ"],
  [/J/g, "து"],
  [/nj/g, "தெ"],
  [/Nj/g, "தே"],
  [/ij/g, "தை"],
  [/j;/g, "த்"],
  [/j/g, "த"],
  [/nes/g, "நௌ"],
  [/Neh/g, "நோ"],
  [/neh/g, "நொ"],
  [/eh/g, "நா"],
  [/ep/g, "நி"],
  [/eP/g, "நீ"],
  [/E}/g, "நூ"],
  [/Eh/g, "நூ"],
  [/E/g, "நு"],
  [/ne/g, "நெ"],
  [/Ne/g, "நே"],
  [/ie/g, "நை"],
  [/e;/g, "ந்"],
  [/e/g, "ந"],
  [/nds/g, "னௌ"],
  [/Ndh/g, "னோ"],
  [/ndh/g, "னொ"],
  [/dh/g, "னா"],
  [/dp/g, "னி"],
  [/dP/g, "னீ"],
  [/D}/g, "னூ"],
  [/Dh/g, "னூ"],
  [/D/g, "னு"],
  [/nd/g, "னெ"],
  [/Nd/g, "னே"],
  [/id/g, "னை"],
  [/d;/g, "ன்"],
  [/d/g, "ன"],
  [/ngs/g, "பௌ"],
  [/Ngh/g, "போ"],
  [/ngh/g, "பொ"],
  [/gh/g, "பா"],
  [/gp/g, "பி"],
  [/gP/g, "பீ"],
  [/G/g, "பு"],
  [/ng/g, "பெ"],
  [/Ng/g, "பே"],
  [/ig/g, "பை"],
  [/g;/g, "ப்"],
  [/g/g, "ப"],
  [/nks/g, "மௌ"],
  [/Nkh/g, "மோ"],
  [/nkh/g, "மொ"],
  [/kh/g, "மா"],
  [/kp/g, "மி"],
  [/kP/g, "மீ"],
  [/K/g, "மு"],
  [/%/g, "மூ"],
  [/nk/g, "மெ"],
  [/Nk/g, "மே"],
  [/ik/g, "மை"],
  [/k;/g, "ம்"],
  [/k/g, "ம"],
  [/nas/g, "யௌ"],
  [/Nah/g, "யோ"],
  [/nah/g, "யொ"],
  [/ah/g, "யா"],
  [/ap/g, "யி"],
  [/aP/g, "யீ"],
  [/A/g, "யு"],
  [/A+/g, "யூ"],
  [/na/g, "யெ"],
  [/Na/g, "யே"],
  [/ia/g, "யை"],
  [/a;/g, "ய்"],
  [/a/g, "ய"],
  [/nus/g, "ரௌ"],
  [/Nuh/g, "ரோ"],
  [/nuh/g, "ரொ"],
  [/uh/g, "ரா"],
  [/up/g, "ரி"],
  [/U/g, "ரு"],
  [/&/g, "ரூ"],
  [/nu/g, "ரெ"],
  [/Nu/g, "ரே"],
  [/iu/g, "ரை"],
  [/u/g, "ர"],
  [/nys/g, "லௌ"],
  [/Nyh/g, "லோ"],
  [/nyh/g, "லொ"],
  [/yh/g, "லா"],
  [/yp/g, "லி"],
  [/yP/g, "லீ"],
  [/Yh/g, "லூ"],
  [/Y}/g, "லூ"],
  [/Y/g, "லு"],
  [/ny/g, "லெ"],
  [/Ny/g, "லே"],
  [/iy/g, "லை"],
  [/y;/g, "ல்"],
  [/y/g, "ல"],
  [/nss/g, "ளௌ"],
  [/Nsh/g, "ளோ"],
  [/nsh/g, "ளொ"],
  [/sh/g, "ளா"],
  [/sP/g, "ளீ"],
  [/Sh/g, "ளூ"],
  [/S/g, "ளு"],
  [/ns/g, "ளெ"],
  [/Ns/g, "ளே"],
  [/is/g, "ளை"],
  [/s;/g, "ள்"],
  [/s/g, "ள"],
  [/ntt/g, "வௌ"],
  [/Nth/g, "வோ"],
  [/nth/g, "வொ"],
  [/th/g, "வா"],
  [/tp/g, "வி"],
  [/tP/g, "வீ"],
  [/nt/g, "வெ"],
  [/Nt/g, "வே"],
  [/it/g, "வை"],
  [/t;/g, "வ்"],
  [/t/g, "வ"],
  [/noo/g, "ழௌ"],
  [/Noh/g, "ழோ"],
  [/noh/g, "ழொ"],
  [/oh/g, "ழா"],
  [/op/g, "ழி"],
  [/oP/g, "ழீ"],
  [/\*/g, "ழூ"],
  [/O/g, "ழு"],
  [/no/g, "ழெ"],
  [/No/g, "ழே"],
  [/io/g, "ழை"],
  [/o;/g, "ழ்"],
  [/o/g, "ழ"],
  [/nws/g, "றௌ"],
  [/Nwh/g, "றோ"],
  [/nwh/g, "றொ"],
  [/wh/g, "றா"],
  [/wp/g, "றி"],
  [/wP/g, "றீ"],
  [/Wh/g, "றூ"],
  [/W}/g, "றூ"],
  [/W/g, "று"],
  [/nw/g, "றெ"],
  [/Nw/g, "றே"],
  [/iw/g, "றை"],
  [/w;/g, "ற்"],
  [/w/g, "ற"],
  [/n``/g, "ஹௌ"],
  [/N`h/g, "ஹோ"],
  [/n`h/g, "ஹொ"],
  [/`h/g, "ஹா"],
  [/`p/g, "ஹி"],
  [/`P/g, "ஹீ"],
  [/n`/g, "ஹெ"],
  [/N`/g, "ஹே"],
  [/i`/g, "ஹை"],
  [/`;/g, "ஹ்"],
  [/`/g, "ஹ"],
  [/n\\s/g, "ஷௌ"],
  [/N\\h/g, "ஷோ"],
  [/n\\h/g, "ஷொ"],
  [/\\h/g, "ஷா"],
  [/\\p/g, "ஷி"],
  [/\\P/g, "ஷீ"],
  [/n\\/g, "ஷெ"],
  [/N\\/g, "ஷே"],
  [/i\\/g, "ஷை"],
  [/\\;/g, "ஷ்"],
  [/\\/g, "ஷ"],
  [/n]s/g, "ஸௌ"],
  [/N]h/g, "ஸோ"],
  [/n]h/g, "ஸொ"],
  [/]h/g, "ஸா"],
  [/]p/g, "ஸி"],
  [/]P/g, "ஸீ"],
  [/n]/g, "ஸெ"],
  [/N]/g, "ஸே"],
  [/i]/g, "ஸை"],
  [/];/g, "ஸ்"],
  [/]/g, "ஸ"],
  [/m/g, "அ"],
  [/M/g, "ஆ"],
  [/</g, "ஈ"],
  [/c/g, "உ"],
  [/C/g, "ஊ"],
  [/v/g, "எ"],
  [/V/g, "ஏ"],
  [/I/g, "ஐ"],
  [/xs/g, "ஔ"],
  [/x/g, "ஒ"],
  [/X/g, "ஓ"],
  [/\//g, "ஃ"],
  [/,/g, "இ"],
  [/=/g, "ஸ்ரீ"],
  [/>/g, ","],
  [/T/g, "வு"],
  [/வு10/g, "வூ"],
  [/G\+/g, "பூ"],
  [/பு10/g, "பூ"],
  [/A\+/g, "யூ"],
  [/யு10/g, "யூ"],
];

function convertLine(text)
{
  if (!text) return text;
  let tempText = text;

  // Pre-normalization for database escaping
  tempText = tempText.replaceAll("\\\\;", "\\;");
  tempText = tempText.replaceAll("\\\\", "\\");
  tempText = tempText.replaceAll("!;", "];");
  tempText = tempText.replaceAll("![", "];");
  tempText = tempText.replaceAll("NT", "Nt");
  tempText = tempText.replaceAll("nT", "nt");
  tempText = tempText.replaceAll("iT", "it");

  // Apply bamini to unicode rules
  for (let i = 0; i < baminiToUnicodeRules.length; i++)
  {
    const [regex, replacement] = baminiToUnicodeRules[i];
    tempText = tempText.replace(regex, replacement);
  }

  return tempText;
}

function baminiToUnicode(text)
{
  if (!text || typeof text !== "string") return text;
  if (/[\u0B80-\u0BFF]/.test(text)) return text;

  // Tag Shielding: split by HTML / slide tags and newlines (<slide...>, <br...>, etc.) and process lines one by one so tags are never mutated
  const segments = text.split(/(<[^>]+>|\r?\n)/g);

  return segments.map(segment => 
  {
    if ((segment.startsWith("<") && segment.endsWith(">")) || segment === "\n" || segment === "\r\n")  return segment;   
    return convertLine(segment);
  }).join("");
}

export
{
  isTamilBibleFont,
  baminiToUnicode
};

export default
{
  isTamilBibleFont,
  baminiToUnicode
};
